# -*- coding: utf-8 -*-
"""Respaldo Gestión de contacto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wndsspW6ZKb38_zed4Vgo95iFnLkYaWa
"""

#1.	Bases del sistema

def main ():
  print("Bienvenido al Menú de contactos")
  print("===============================")
  print("Me puedes decir tú nombre?")
  nombre = input()
  print("Hola", nombre)
  print("a continuación tendras un menú de opciones para gestionar tus contactos")
  print("¡Buen día!")

main()

#2.	Mostrar menú principal

print("1. Agregar contactos")
print("2. Buscar contactos")
print("3. Editar contactos")
print("4. Eliminar contactos")
print("5. Ver contactos guardados")
print("9. Saliendo....que tengas buen día \U0001F600")

#3.	Leer opción del usuario

opcion = int(input("Elige una opción: "))
if opcion == 1:
  print("Has elegido la opción 1, que corresponde a Agregar contacto")
elif opcion == 2:
  print("Has elegido la opción 2, que corresponde a Buscar contacto")
elif opcion == 3:
  print("Has elegido la opción 3, que corresponde a Editar contacto")
elif opcion == 4:
  print("Has elegido la opción 4, que corresponde a Eliminar contactos")
elif opcion == 5:
  print("Has elegido la opción 5, que corresponde a revisar contactos guardados")
elif opcion == 9:
  print("Has elegido la opción 9, que corresponde a Salir")
else:
  print("Opción no válida. Por favor puedes seleccionar una opción del menú")

#4.	Ejecutar acción solicitada por usuario

class ContactoModel:
    def __init__(self, nombre, telefono, correo, direccion) -> None:
        self.nombre = nombre
        self.telefono = telefono
        self.correo = correo
        self.direccion = direccion

class Agenda:
    def __init__(self) -> None:
        self.contacto: list = []

    def agregar_contactos(self):
        print( "Has elegido la opción 1, que corresponde a Agregar contactos" )
        print( "------------------------------------------------------------" )
        print()

        nombre = input( "Por favor ingresa el Nombre: " )
        telefono = input( "Por favor ingresa el Teléfono: " )
        correo = input( "Por favor ingresa el Correo: " )
        direccion = input( "Por favor ingresa la Dirección: " )


        nuevo_contacto = ContactoModel( nombre, telefono, correo, direccion )
        self.contacto.append( nuevo_contacto )

        print( "El Contacto fue agregado exitosamente." )
        print()

    def buscar_contactos(self) -> bool:
        print( "Has elegido la opción 2, que corresponde a Buscar contactos" )
        print( "-----------------------------------------------------------" )
        print()

        buscar = input( "Por favor puedes Ingresar el nombre/teléfono del contacto para buscar: " )
        encontrado = False
        for contacto in self.contacto:
            if contacto.nombre == buscar or contacto.telefono == buscar:
                print( f"Nombre: {contacto.nombre}" )
                print( f"Teléfono: {contacto.telefono}" )
                print( f"Correo: {contacto.correo}" )
                print( f"Dirección: {contacto.direccion}" )
                encontrado = True
                break
        if not encontrado:
            print( "El Contacto no fue encontrado, serás devuelto al menú" )
            print()
        return encontrado


    def editar_contactos(self):
        print( "Necesitas Editar el contacto?" )
        print()

    def eliminar_contactos(self):
        print( "Necesitas Eliminar el contacto?" )
        print()

    def ver_contactos_guardados(self):
        print( "Quieres revisar los contactos guardados?" )
        print( "----------------------------------------" )
        print()

        if len( self.contacto ) == 0:
            print( "No hay contactos registrados." )
            print()
        else:
            for contacto in self.contacto:
                print( f"Nombre: {contacto.nombre}" )
                print( f"Teléfono: {contacto.telefono}" )
                print( f"Correo: {contacto.correo}" )
                print( f"Dirección: {contacto.direccion}" )
                print( "--------------------------------" )
                print()

def main():
    print( "Bienvenido al Menú de contactos" )
    print("=================================")
    print()
    print()
    print("Me puedes decir tú nombre?")
    nombre = input()
    print("Hola", nombre)
    print("A continuación tendrás un menú de opciones para gestionar tus contactos")
    print()

    # Opciones del menú
    print("1. Agregar contactos")
    print("2. Buscar contactos")
    print("3. Editar contactos")
    print("4. Eliminar contactos")
    print("5. Ver contactos guardados")
    print("9. Saliendo....")
    print()
    print()


    agenda = Agenda()
    opcion = ""
    while opcion != 9:
        opcion = int( input( "Seleccione una opción: " ) )

        if opcion == 1:
            agenda.agregar_contactos()
        elif opcion == 2:
            agenda.buscar_contactos()
        elif opcion == 3:
            agenda.editar_contactos()
        elif opcion == 4:
            agenda.eliminar_contactos()
        elif opcion == 5:
            agenda.ver_contactos_guardados()
        elif opcion == 9:
            print( "Saliendo del sistema...que tengas buen día \U0001F600" )
        else:
            print( "Opción no válida. Por favor, seleccione una opción del menú." )

if __name__ == "__main__":
    main()